### ISSUE TITLE
PHP Version requirement

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2-model-collection#2]
Yii 2 requires PHP 5.4, but this requires at least 5.5, I'd suggest, if you are using a stricter requirement than Yii 2 anyway, to just go with 7.0 or 7.1. (Since that is where Yii 2.1 will go as well)

**Comment by cebe** [comment]
I see no problem in an extension requiring a higher PHP version than the framework if it uses the PHP features (which is the case for the generator collection). I is written for 2.0 because there is no 2.1 yet. Of course there will be a version for 2.1 too if it turns out this extension is useful.
